import type { Database } from '@/types/database.types';

export type ModelSourceSeed = Database['public']['Tables']['model_sources']['Insert'];

export const MODEL_SOURCE_SEED: ModelSourceSeed[] = [
  {
    id: '18052cd9-2fea-407b-a869-dd7725d55f9d',
    vendor: 'OpenAI',
    model_name: 'GPT-4o',
    primary_url: 'https://openai.com/index/gpt-4o/',
    rss_url: 'https://openai.com/blog/rss',
    keywords: ['openai', 'gpt-4o', 'gpt4o'],
    fallback_queries: ['OpenAI GPT-4o launch', 'GPT-4o pricing and capabilities'],
    mirrors: ['https://r.jina.ai/{{raw}}'],
    mirrored_assets: ['https://cdn.openai.com/papers/GPT-4o-system-card.pdf'],
    press_pdfs: ['https://cdn.openai.com/papers/GPT-4o-system-card.pdf'],
    docs_url: 'https://platform.openai.com/docs/models/gpt-4o',
    api_ref: 'https://api.openai.com/v1/models',
    freshness_interval_hours: 12,
    needs_proxy: true,
    priority: 10,
    last_verified_at: null,
    created_at: null
  },
  {
    id: '28f56163-bc67-4310-9914-039037b19acd',
    vendor: 'OpenAI',
    model_name: 'GPT-4o Mini',
    primary_url: 'https://openai.com/index/gpt-4o-mini/',
    rss_url: 'https://openai.com/blog/rss',
    keywords: ['openai', 'gpt-4o mini', 'gpt4o mini'],
    fallback_queries: ['GPT-4o mini announcements', 'GPT-4o mini pricing'],
    mirrors: ['https://r.jina.ai/{{raw}}'],
    mirrored_assets: ['https://cdn.openai.com/papers/GPT-4o-system-card.pdf'],
    press_pdfs: [],
    docs_url: 'https://platform.openai.com/docs/models/gpt-4o-mini',
    api_ref: 'https://api.openai.com/v1/models',
    freshness_interval_hours: 12,
    needs_proxy: true,
    priority: 9,
    last_verified_at: null,
    created_at: null
  },
  {
    id: '802711b9-821f-4f1d-8b17-e976d795485c',
    vendor: 'Anthropic',
    model_name: 'Claude 3.5 Sonnet',
    primary_url: 'https://www.anthropic.com/news/claude-3-5-sonnet',
    rss_url: 'https://www.anthropic.com/news/rss.xml',
    keywords: ['anthropic', 'claude', 'claude 3.5', 'sonnet'],
    fallback_queries: ['Anthropic Claude 3.5 Sonnet summary', 'Claude 3.5 Sonnet benchmarks'],
    mirrors: ['https://r.jina.ai/{{raw}}'],
    mirrored_assets: ['https://r.jina.ai/https://www.anthropic.com/news/claude-3-5-sonnet'],
    press_pdfs: [],
    docs_url: 'https://docs.anthropic.com/en/docs/about-claude/models',
    api_ref: 'https://api.anthropic.com/v1/models',
    freshness_interval_hours: 24,
    needs_proxy: false,
    priority: 8,
    last_verified_at: null,
    created_at: null
  },
  {
    id: '3e78b4a3-b928-47d8-81c0-3e45e2c9ef96',
    vendor: 'Google',
    model_name: 'Gemini 1.5 Pro / Flash',
    primary_url: 'https://ai.google.dev/gemini-api/docs/models/gemini',
    rss_url: 'https://blog.google/rss/',
    keywords: ['google', 'gemini', 'gemini pro', 'gemini flash'],
    fallback_queries: ['Google Gemini 1.5 release notes', 'Gemini Flash pricing'],
    mirrors: ['https://r.jina.ai/{{raw}}'],
    mirrored_assets: ['https://ai.google/static/documents/gemini_1p5_report.pdf'],
    press_pdfs: ['https://ai.google/static/documents/gemini_1p5_report.pdf'],
    docs_url: 'https://ai.google.dev/gemini-api/docs/models',
    api_ref: 'https://ai.google.dev/gemini-api/docs/models',
    freshness_interval_hours: 24,
    needs_proxy: false,
    priority: 7,
    last_verified_at: null,
    created_at: null
  },
  {
    id: 'ffa650c2-cd84-40db-b2b6-02f695b51a3e',
    vendor: 'Meta',
    model_name: 'Llama 3.1',
    primary_url: 'https://ai.meta.com/blog/meta-llama-3-1/',
    rss_url: 'https://ai.meta.com/blog/rss/',
    keywords: ['meta', 'llama 3', 'llama 3.1'],
    fallback_queries: ['Meta Llama 3.1 capabilities', 'Llama 3.1 release details'],
    mirrors: ['https://r.jina.ai/{{raw}}'],
    mirrored_assets: ['https://huggingface.co/meta-llama/Llama-3.1-405B'],
    press_pdfs: [],
    docs_url: 'https://ai.meta.com/llama/',
    api_ref: 'https://api.llama-api.com/v1/models',
    freshness_interval_hours: 48,
    needs_proxy: false,
    priority: 6,
    last_verified_at: null,
    created_at: null
  },
  {
    id: '31fddfae-6061-46e4-985e-872e5ce66304',
    vendor: 'Mistral',
    model_name: 'Mistral Large 2',
    primary_url: 'https://mistral.ai/news/mistral-large-2407/',
    rss_url: 'https://mistral.ai/feed.xml',
    keywords: ['mistral', 'mistral large', 'mistral 2'],
    fallback_queries: ['Mistral Large 2 roadmap', 'Mistral Large availability'],
    mirrors: ['https://r.jina.ai/{{raw}}'],
    mirrored_assets: ['https://cdn.mistral.ai/mistral-large.pdf'],
    press_pdfs: [],
    docs_url: 'https://docs.mistral.ai/',
    api_ref: 'https://api.mistral.ai/v1/models',
    freshness_interval_hours: 48,
    needs_proxy: false,
    priority: 5,
    last_verified_at: null,
    created_at: null
  },
  {
    id: 'a214f23a-5e07-4626-9a1d-9b7b765b992c',
    vendor: 'Cohere',
    model_name: 'Command R+',
    primary_url: 'https://cohere.com/blog/command-r-plus',
    rss_url: 'https://cohere.com/blog/rss.xml',
    keywords: ['cohere', 'command r', 'command r+'],
    fallback_queries: ['Cohere Command R+ features', 'Command R+ evaluation'],
    mirrors: ['https://r.jina.ai/{{raw}}'],
    mirrored_assets: ['https://cohere.com/assets/command-r-plus.pdf'],
    press_pdfs: [],
    docs_url: 'https://docs.cohere.com/docs/models',
    api_ref: 'https://api.cohere.com/v1/models',
    freshness_interval_hours: 72,
    needs_proxy: false,
    priority: 4,
    last_verified_at: null,
    created_at: null
  }
];
